runs_on: machine
version: 2

jobs:
  main:
  - name: Build with dioxus
    working_dir: ${{bld_project_dir}}/browser/keycrab_ext
    exec:
    - dioxus build --release

  - name: Rerun tailwind build with release
    working_dir: ${{bld_project_dir}}/browser/keycrab_ext/scripts
    exec:
    - npm run build-release

  - name: Remove any old files
    working_dir: ${{bld_project_dir}}/browser/ff
    exec:
    - rm -r ./assets || true
    - rm ./index.html || true
    - rm ./index.js || true
    - rm ./tailwind.css || true
    - rm ./fill_form.js || true

  - name: Copy artifacts
    working_dir: ${{bld_project_dir}}/browser/keycrab_ext/dist
    exec: 
      - mkdir ${{bld_project_dir}}/dist/extension || true
      - cp -r ./assets ${{bld_project_dir}}/dist/extension
      - cp ./index.html ${{bld_project_dir}}/dist/extension
      - cp ./tailwind.css ${{bld_project_dir}}/dist/extension
      - cp ./index.js ${{bld_project_dir}}/dist/extension
      - cp ./fill_form.js ${{bld_project_dir}}/dist/extension
